In [8]:
import requests
import pandas as pd
import io
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
d = {'a':5,
     'b':10}

In [3]:
our_req = requests.get('http://127.0.0.1:8000/',params=d)

In [4]:
our_req.json()

{'its': 15}

In [5]:
number = {'a':10,
          'b':15,
          'c':5}

In [6]:
second_req = requests.get('http://127.0.0.1:8000/compyt',params=number)

In [7]:
second_req.json()

'right'

In [8]:
my_age = {'a':10,
          'b':10,
          'c':5}

In [9]:
tree_req = requests.post('http://127.0.0.1:8000/p',params=my_age)

In [10]:
tree_req.json()

{'i am': 25}

In [11]:
for_our_class = {'a':10,
          'b':10,
          'c':5}

In [12]:
four_req = requests.post('http://127.0.0.1:8000/d',json=for_our_class)

In [13]:
four_req.json()

{'answer': 8.333333333333334}

In [14]:
for_put = {'id': 19, 'name': 'Anna', 'last_name': 'Hall'}

In [15]:
its_put = requests.put('http://127.0.0.1:8000/put', json=for_put)

In [16]:
its_put.json()

{'id': 19, 'name': 'Anna', 'last_name': 'Hall'}

In [17]:
for_patch = {'name': 'Sasha'}

In [18]:
its_patch = requests.patch('http://127.0.0.1:8000/patch/1',json=for_patch)

In [19]:
its_patch.json()

{'id': 1, 'name': 'Sasha', 'last_name': 'Smith'}

In [20]:
its_delete = requests.delete("http://127.0.0.1:8000/users/1")

In [21]:
its_delete.json()

'its work'

In [2]:
df = pd.read_csv('data/nhl_dataset.csv')
df

,won,game_id,date,season,venue,attendance,officials,season_series,spread,over_under,...,opp_rolling_pim_10,opp_rolling_giveaways_3,opp_rolling_giveaways_10,opp_rolling_takeaways_3,opp_rolling_takeaways_10,opp_rolling_pp_efficiency_3,opp_rolling_pp_efficiency_10,save_pct,is_home,rest_advantage
0,1,401685330,2024-10-01 23:00:00+00:00,2025,TD Garden,17850.0,Ryan Daisy|James Tobias|Mitch Dunning|Michael ...,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.928571,1,0.0
1,0,401685338,2024-10-03 23:00:00+00:00,2025,Videotron Centre,17334.0,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.846154,0,-1.0
2,0,401685352,2024-10-05 21:00:00+00:00,2025,Capital One Arena,13224.0,Kelly Sutherland|Tommy Hughes|Justin Kea|Ryan ...,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.937500,0,-2.0
3,0,401687603,2024-10-08 23:00:00+00:00,2025,Amerant Bank Arena,19813.0,Kelly Sutherland|TJ Luxmore|Devin Berg|Julien ...,FLA leads series 1-0,NaN,0.0,...,9.500000,8.500000,8.5,4.000000,4.000000,0.500000,0.500000,0.828571,0,0.0
4,1,401687610,2024-10-10 23:00:00+00:00,2025,TD Garden,17850.0,Dan Kelly|Wes McCauley|Tyson Baker|Michael Mar...,BOS leads series 1-0,NaN,0.0,...,17.716667,11.000000,11.0,3.666667,3.666667,0.066667,0.066667,0.833333,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,1,401773321,2025-05-22 00:00:00+00:00,2025,American Airlines Center,18532.0,Scott Cherrey|Jean Hebert|Francis Charron|Wes ...,DAL wins series 2-1,NaN,0.0,...,7.700000,14.000000,14.5,4.666667,3.700000,0.166667,0.272727,0.888889,1,-2.0
2882,0,401773322,2025-05-24 00:00:00+00:00,2025,American Airlines Center,18532.0,Jonny Murray|Jean Hebert|Dan O'Rourke|Garrett ...,DAL wins series 2-1,NaN,0.0,...,7.100000,14.666667,14.9,5.666667,3.700000,0.142857,0.318182,0.880000,1,0.0
2883,0,401773323,2025-05-25 19:00:00+00:00,2025,Rogers Place,18347.0,Kelly Sutherland|Eric Furlatt|Jonny Murray|Mat...,DAL wins series 2-1,NaN,0.0,...,7.100000,16.000000,14.9,4.666667,3.700000,0.200000,0.240000,0.750000,0,0.0
2884,0,401773324,2025-05-28 00:00:00+00:00,2025,Rogers Place,18347.0,Ryan Gibbons|Chris Rooney|Dan O'Rourke|Matt Ma...,DAL wins series 2-1,NaN,0.0,...,7.100000,15.666667,14.6,4.333333,3.300000,0.272727,0.200000,0.878788,0,0.0
2885,0,401773325,2025-05-30 00:00:00+00:00,2025,American Airlines Center,18532.0,Ryan Gibbons|Scott Cherrey|Chris Rooney|Franci...,DAL wins series 2-1,NaN,0.0,...,7.300000,11.333333,13.8,4.333333,3.900000,0.363636,0.269231,0.739130,1,0.0

In [3]:
df = df.drop(['season'],axis=1)
df = df.drop(['game_id','officials','spread',],axis=1)
df = df.drop('over_under',axis=1)
df = df.drop(['season_series'],axis=1)
df = df.drop(columns = ['favorite_moneyline','team_record', 'score', 'shots',
        'power_play_goals', 'power_play_opportunities', 'faceoff_win_pct',
        'hits', 'blocked_shots', 'pim'])
df = df.drop(columns=['giveaways', 'takeaways'])
df = df.drop(columns=['cum_wins','cum_games'])
df = df.drop(columns=['save_pct','opp_score','opp_shots','rest_advantage'])
df = df.drop(columns = ['rolling_score_3',
        'rolling_power_play_goals_3', 'rolling_power_play_opportunities_3',
        'rolling_faceoff_win_pct_3', 'rolling_hits_3',
        'rolling_blocked_shots_3', 'rolling_shots_3', 'rolling_pim_3',
        'rolling_giveaways_3', 'rolling_takeaways_3', 'rolling_pp_efficiency_3',
        'rolling_score_10', 'rolling_power_play_goals_10',
        'rolling_power_play_opportunities_10', 'rolling_faceoff_win_pct_10',
        'rolling_hits_10', 'rolling_blocked_shots_10', 'rolling_shots_10',
        'rolling_pim_10', 'rolling_giveaways_10', 'rolling_takeaways_10',
        'rolling_pp_efficiency_10'])
df = df.drop(columns=['season_win_pct'])
df['date']=pd.to_datetime(df['date'])
df = df.drop(columns=['team_id','home_away','opp_team_id'])
df['year']= df['date'].dt.year
df['month'] = df['date'].dt.month
df['dayofweek']= df['date'].dt.dayofweek
df['day']=df['date'].dt.day
df['hour']=df['date'].dt.hour
df = df.drop(['date'],axis=1)
df

,won,venue,attendance,team_name,rest_days,opp_team_name,opp_won,opp_rest_days,opp_season_win_pct,opp_rolling_score_3,...,opp_rolling_takeaways_3,opp_rolling_takeaways_10,opp_rolling_pp_efficiency_3,opp_rolling_pp_efficiency_10,is_home,year,month,dayofweek,day,hour
0,1,TD Garden,17850.0,Boston Bruins,3.0,Philadelphia Flyers,0,3.0,0.450000,NaN,...,NaN,NaN,NaN,NaN,1,2024,10,1,1,23
1,0,Videotron Centre,17334.0,Boston Bruins,2.0,Los Angeles Kings,1,3.0,0.450000,NaN,...,NaN,NaN,NaN,NaN,0,2024,10,3,3,23
2,0,Capital One Arena,13224.0,Boston Bruins,1.0,Washington Capitals,1,3.0,0.450000,NaN,...,NaN,NaN,NaN,NaN,0,2024,10,5,5,21
3,0,Amerant Bank Arena,19813.0,Boston Bruins,3.0,Florida Panthers,1,3.0,394.500000,3.000000,...,4.000000,4.000000,0.500000,0.500000,0,2024,10,1,8,23
4,1,TD Garden,17850.0,Boston Bruins,2.0,Montreal Canadiens,0,1.0,11.666667,2.000000,...,3.666667,3.666667,0.066667,0.066667,1,2024,10,3,10,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,1,American Airlines Center,18532.0,Dallas Stars,4.0,Edmonton Oilers,0,6.0,13.221053,2.333333,...,4.666667,3.700000,0.166667,0.272727,1,2025,5,3,22,0
2882,0,American Airlines Center,18532.0,Dallas Stars,2.0,Edmonton Oilers,1,2.0,13.083333,2.333333,...,5.666667,3.700000,0.142857,0.318182,1,2025,5,5,24,0
2883,0,Rogers Place,18347.0,Dallas Stars,1.0,Edmonton Oilers,1,1.0,12.958763,2.333333,...,4.666667,3.700000,0.200000,0.240000,0,2025,5,6,25,19
2884,0,Rogers Place,18347.0,Dallas Stars,2.0,Edmonton Oilers,1,2.0,12.836735,4.000000,...,4.333333,3.300000,0.272727,0.200000,0,2025,5,2,28,0
2885,0,American Airlines Center,18532.0,Dallas Stars,2.0,Edmonton Oilers,1,2.0,12.717172,4.333333,...,4.333333,3.900000,0.363636,0.269231,1,2025,5,4,30,0

In [4]:
df = df.drop(columns=['opp_season_win_pct', 'opp_rolling_score_3',
       'opp_rolling_score_10', 'opp_rolling_power_play_goals_3',
       'opp_rolling_power_play_goals_10',
       'opp_rolling_power_play_opportunities_3',
       'opp_rolling_power_play_opportunities_10',
       'opp_rolling_faceoff_win_pct_3', 'opp_rolling_faceoff_win_pct_10',
       'opp_rolling_hits_3', 'opp_rolling_hits_10',
       'opp_rolling_blocked_shots_3', 'opp_rolling_blocked_shots_10',
       'opp_rolling_shots_3', 'opp_rolling_shots_10', 'opp_rolling_pim_3',
       'opp_rolling_pim_10', 'opp_rolling_giveaways_3',
       'opp_rolling_giveaways_10', 'opp_rolling_takeaways_3',
       'opp_rolling_takeaways_10', 'opp_rolling_pp_efficiency_3',
       'opp_rolling_pp_efficiency_10','attendance'])
df

,won,venue,team_name,rest_days,opp_team_name,opp_won,opp_rest_days,is_home,year,month,dayofweek,day,hour
0,1,TD Garden,Boston Bruins,3.0,Philadelphia Flyers,0,3.0,1,2024,10,1,1,23
1,0,Videotron Centre,Boston Bruins,2.0,Los Angeles Kings,1,3.0,0,2024,10,3,3,23
2,0,Capital One Arena,Boston Bruins,1.0,Washington Capitals,1,3.0,0,2024,10,5,5,21
3,0,Amerant Bank Arena,Boston Bruins,3.0,Florida Panthers,1,3.0,0,2024,10,1,8,23
4,1,TD Garden,Boston Bruins,2.0,Montreal Canadiens,0,1.0,1,2024,10,3,10,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,1,American Airlines Center,Dallas Stars,4.0,Edmonton Oilers,0,6.0,1,2025,5,3,22,0
2882,0,American Airlines Center,Dallas Stars,2.0,Edmonton Oilers,1,2.0,1,2025,5,5,24,0
2883,0,Rogers Place,Dallas Stars,1.0,Edmonton Oilers,1,1.0,0,2025,5,6,25,19
2884,0,Rogers Place,Dallas Stars,2.0,Edmonton Oilers,1,2.0,0,2025,5,2,28,0
2885,0,American Airlines Center,Dallas Stars,2.0,Edmonton Oilers,1,2.0,1,2025,5,4,30,0

In [2]:
df = pd.read_csv('test_data')
y = df['attendance']
X = df.drop(['attendance'],axis=1)
X_train, X_eval, y_train, y_eval = train_test_split(X, y, test_size=0.2,random_state=42)

In [5]:
X_eval_encode = X_eval.to_csv()
file_like = io.BytesIO(X_eval_encode.encode('utf-8'))
files = {'file': ('data.csv', file_like, 'text/csv')}
test = requests.post("http://127.0.0.1:8000/model",files=files)

In [6]:
ansver = pd.DataFrame(test.json())
ansver

      predictions
0    15670.108200
1    18811.047976
2    16017.165601
3    19073.537751
4    18787.507319
..            ...
522  18579.486786
523  18878.738990
524  18010.110264
525  17884.060350
526  16547.322145

[527 rows x 1 columns]

In [9]:
r = r2_score(ansver,y_eval)
r

0.8666534528796417

In [ ]:
0.8666534528796417

,Unnamed: 0,won,venue,team_name,rest_days,opp_team_name,opp_won,opp_rest_days,is_home,year,month,dayofweek,day,hour,predictions
0,0,1,TD Garden,Boston Bruins,3.0,Philadelphia Flyers,0,3.0,1,2024,10,1,1,23,17831.135596
1,1,0,Videotron Centre,Boston Bruins,2.0,Los Angeles Kings,1,3.0,0,2024,10,3,3,23,17261.165905
2,2,0,Capital One Arena,Boston Bruins,1.0,Washington Capitals,1,3.0,0,2024,10,5,5,21,17448.263962
3,3,0,Amerant Bank Arena,Boston Bruins,3.0,Florida Panthers,1,3.0,0,2024,10,1,8,23,19733.889404
4,4,1,TD Garden,Boston Bruins,2.0,Montreal Canadiens,0,1.0,1,2024,10,3,10,23,17954.845760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,2881,1,American Airlines Center,Dallas Stars,4.0,Edmonton Oilers,0,6.0,1,2025,5,3,22,0,18659.548636
2882,2882,0,American Airlines Center,Dallas Stars,2.0,Edmonton Oilers,1,2.0,1,2025,5,5,24,0,18565.419063
2883,2883,0,Rogers Place,Dallas Stars,1.0,Edmonton Oilers,1,1.0,0,2025,5,6,25,19,18325.376562
2884,2884,0,Rogers Place,Dallas Stars,2.0,Edmonton Oilers,1,2.0,0,2025,5,2,28,0,18285.370640
2885,2885,0,American Airlines Center,Dallas Stars,2.0,Edmonton Oilers,1,2.0,1,2025,5,4,30,0,18621.527389